import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=Deno.env.get('SUPABASE_URL')!; const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!; const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const H={...CORS,'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'"};
const buckets=new Map<string,{count:number;reset:number}>();
function json(body:unknown,status=200,extra:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{...H,...extra}})}
function ip(req:Request){return req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown'}
function limited(key:string,limit:number){const now=Date.now(),c=buckets.get(key);if(!c||c.reset<=now){buckets.set(key,{count:1,reset:now+60000});return 0}c.count++;return c.count>limit?Math.max(1,Math.ceil((c.reset-now)/1000)):0}
function magic(bytes:Uint8Array,type:string){if(type==='application/pdf')return bytes.length>=5&&new TextDecoder().decode(bytes.slice(0,5))==='%PDF-';if(type==='image/jpeg')return bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==='image/png')return bytes.length>=8&&bytes.slice(0,8).every((v,i)=>v===[137,80,78,71,13,10,26,10][i]);if(type==='image/webp')return bytes.length>=12&&new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';return false}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const retry=limited(ip(req),8);if(retry)return json({error:'rate_limited'},429,{'Retry-After':String(retry)});try{const ct=req.headers.get('content-type')||'';if(!ct.toLowerCase().startsWith('multipart/form-data'))return json({error:'multipart_required'},415);const form=await req.formData();const token=String(form.get('token')||'').trim().toLowerCase();const file=form.get('file');if(!/^[a-f0-9]{64}$/.test(token))return json({error:'invalid_token'},400);const tokenRetry=limited(`token:${token}`,3);if(tokenRetry)return json({error:'rate_limited'},429,{'Retry-After':String(tokenRetry)});if(!(file instanceof File))return json({error:'file_required'},400);if(file.size<1||file.size>10*1024*1024)return json({error:'file_too_large'},413);const allowed=new Set(['application/pdf','image/jpeg','image/png','image/webp']);if(!allowed.has(file.type))return json({error:'unsupported_file_type'},415);const{data:inv,error:lookupErr}=await db.rpc('get_invoice_by_token',{p_public_token:token});if(lookupErr||!inv||!inv.id)return json({error:'invoice_not_found'},404);if(!['issued','payment_submitted'].includes(inv.status))return json({error:'invoice_not_payable'},409);if(inv.pop_path)return json({error:'pop_already_submitted'},409);const ext=file.type==='application/pdf'?'pdf':file.type.split('/')[1]||'bin';const path=`invoices/${inv.id}/${crypto.randomUUID()}.${ext}`;const bytes=new Uint8Array(await file.arrayBuffer());if(!magic(bytes,file.type))return json({error:'file_content_mismatch'},415);const{error:uploadErr}=await db.storage.from('pop-files').upload(path,bytes,{contentType:file.type,upsert:false});if(uploadErr)return json({error:'upload_failed'},500);const{data:updated,error:updateErr}=await db.from('invoices').update({status:'payment_submitted',payment_submitted_at:new Date().toISOString(),pop_path:path,updated_at:new Date().toISOString()}).eq('id',inv.id).eq('status','issued').is('pop_path',null).select('id').maybeSingle();if(updateErr||!updated){await db.storage.from('pop-files').remove([path]);return json({error:updateErr?'invoice_update_failed':'pop_already_submitted'},updateErr?500:409)}const{error:eventErr}=await db.rpc('record_invoice_event',{p_invoice_id:inv.id,p_event_type:'PAYMENT_SUBMITTED',p_actor_type:'customer',p_metadata:{file_type:file.type,file_size:file.size}});if(eventErr){console.error('invoice-pop-upload event failed',eventErr);return json({ok:true,status:'payment_submitted',audit_event_warning:true});}return json({ok:true,status:'payment_submitted'});}catch(e){console.error('invoice-pop-upload failed',e);return json({error:'request_failed'},400)}});
